name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: morrisoncole/pr-lint-action@v1.1.1
      with:
        title-regex: '(\[Internal\]|\[v4\] )?.{3}.+: (Adds|Fixes|Refactors) .{3}.+'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        on-failed-regex-comment: >
         Please follow the required format: \"[Internal] Category: (Adds|Fixes|Refactors) Description\"<br /><br />
         Examples:<br />
         Diagnostics: Adds GetElapsedClientLatency to CosmosDiagnostics<br/> 
         PartitionKey: Fixes null reference when using default(PartitionKey)<br/> 
         [v4] Client Encryption: Refactors code to external project<br/>
         [Internal] Query: Adds code generator for CosmosNumbers for easy additions in the future.<br/>
